language: generic

env:
  global:
    - CI="true"

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x ./build-package.sh
  - ./build-package.sh

jobs:
  include:
    - stage: test ğŸ‘©ğŸ¾â€ğŸ’»
      env: ATOM_CHANNEL=stable
      os: linux
    - stage: test ğŸ‘©ğŸ¾â€ğŸ’»
      env: ATOM_CHANNEL=beta
      os: linux
    - stage: test ğŸ‘©ğŸ¾â€ğŸ’»
      env: ATOM_CHANNEL=stable
      os: osx
    - stage: test ğŸ‘©ğŸ¾â€ğŸ’»
      env: ATOM_CHANNEL=beta
      os: osx

    - stage: lint âœ¨
      script:
        - npm install
        - npm run lint

    - stage: release ğŸ‰
      if: branch = master && type != pull_request
      script:
        - nvm install lts/*
        - chmod u+x ./semantic-release.sh
        - ./semantic-release.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: xenial

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
    - libgconf-2-4
